---
title: "Data generation—CR25 staff"
pkgdown:
  as_is: true
---

## Introduction

This file describes the values in the synthetic data file "CR25_staff_list.xls". This file is the list of all staff of the fictional wholesale company, CR25 (for "Classic Rock 25"). This file can be linked to the survey data file [SPSS file name here]. 

### Variables

* Last name

* First name

* Employee ID

* Date of birth

* Canadian employee equity group

* Date of hire

* Classification group

* Occupation

* Department

### Setup

_Are there any random variables?_




The first step is to install the necessary packages. The seed is set to [a number associated with a classic rock staple](https://www.youtube.com/watch?v=axLRUszuu9I), so that future runs of the code will generate the same data table. This is important, as some of the examples in the book are based on summary tables drawn from the master file.

```{r setup, warning=FALSE, message=FALSE}
# tidyverse packages
library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
#
# utilities
set.seed(8675309)

```


### Input data


-30-


